### ISSUE TITLE
### Analysis

### ISSUE THREAD

**Issue by mike7866** [google/google-toolbox-for-mac#359]
### Analysis
```yml
Action Name: reimagined/github-actions/install-cloud
Action Type: Node
GITHUB_TOKEN Matches: token,GITHUB_TOKEN
Stars: 0
Private: false
Forks: 1
```

__Originally posted by @step-security-bot in https://github.com/step-security/secure-workflows/issues/1580#issuecomment-1332221215__

__Originally posted by @mike7866 in https://github.com/Skattermuffin/hey-game-pepople-i-know-you-r-ment-to-like-make-these-long-but-come-on-its-fun-but-arrow-game-lol/issues/5__
